### ISSUE TITLE
This git repository is 136MB?!

### ISSUE THREAD

**Issue by fpemud** [erocarrera/pefile#82] opened 2016-01-15 23:39 UTC
I'm astonished that 136MB data is downloaded when cloning this repository.

```
fpemud@fpemud-workstation ~/codes $ git clone http://github.com/erocarrera/pefile
Cloning into 'pefile'...
remote: Counting objects: 485, done.
remote: Total 485 (delta 0), reused 0 (delta 0), pack-reused 485
Receiving objects: 100% (485/485), 136.11 MiB | 73.00 KiB/s, done.
Resolving deltas: 100% (274/274), done.
Checking connectivity... done.
```

**Comment by nyx0** [comment] 2016-01-16 17:30
If I'm not mistaken these 3 commits are quite heavy.
```
d657f84
f7498a3
aec6c46
```

**Comment by RyPeck** [comment] 2016-01-19 02:41
One of the biggest files is in the develop branch - `tests/test_data.tar.bz2.enc`. Contains some test files for the CI.

I personally wish that this wasn't encrypted.

**Comment by JonathonReinhart** [comment] 2016-02-09 19:03
Why, oh why would there be encrypted data in a Git repository?  Please tell me there is not live malware contained in that tarball.

**Comment by RyPeck** [comment] 2016-02-09 21:12
@JonathonReinhart this code gets run on malware a lot - I hope there is malware in the encrypted and compressed test file.

**Comment by JonathonReinhart** [comment] 2016-02-09 23:57
@RyPeck Of course it's used for malware. But you can absolutely test a library like `pefile` without having actual, live malware checked into the repo. If there's some technique being used by malware that `pefile` has been modified to test, then a PE file should be created that mimics just that technique.

A good way to avoid having large binaries checked-in, just for the sake of unit testing, is to have scripts/source code which generates those input files.

**Comment by erocarrera** [comment] 2016-03-03 23:27
Those files encrypted data blobs contain malware and proprietary PEs than can't be publicly released. They are the bulk of the regression tests of pefile as they exercise most of the edge-cases it has had to consider.
travis-ci.org supports working with encrypted blobs for the tests, which is fantastic and has allowed me to move the regression testing to their system.

**Closed** 2016-03-03 23:28 UTC
Labels: wontfix

**Comment by pombredanne** [comment] 2017-05-03 13:04
@erocarrera from what I see these test files are:
1. well known binaries from MSFT
2. other test and malware binaries

Would it be fair to assume that several of these may be available publicly elsewhere? So may you could at least do some of these?
1. document where these are from
2. keep the expected dumps un-encrypted

And may also include PEs that would not be encrypted and would be from public/open source origins?

**Comment by pombredanne** [comment] 2017-05-03 17:41
FWIW see this comment: https://github.com/erocarrera/pefile/issues/171#issuecomment-298948927
I recreated a test suite for pefile https://github.com/viper-framework/pefile-tests/ to help with @Rafiot Python3 improvements

**Comment by pombredanne** [comment] 2017-05-04 13:57
I am making any further related comments in #171 ... since this issue is closed.
